### ISSUE TITLE
Failure when trying to integrate the code with ROS

### ISSUE THREAD

**Issue by davidsanchezf** [simondlevy/ARDroneAutoPylot#1]
Hi!

I am trying to publish camera frames into a ROStopic, so I modified autopylot_agent.py as you can see below:

```
import numpy as np
import cv2
import rospy
from sensor_msgs.msg import Image
import cv_bridge

rospy.init_node('dron_camera')
pub = rospy.Publisher('frame', Image,queue=10)
bridge = cv_bridge.CVBridge()

def action(img_bytes, img_width, img_height, is_belly, \
    ctrl_state, vbat_flying_percentage, theta, phi, psi, altitude, vx, vy):

    # Report navigation data
    print('ctrl state=%6d battery=%2d%% theta=%+f phi=%+f psi=%+f altitude=%+3d vx=%f vy=%+f' % \
                          (ctrl_state, vbat_flying_percentage, theta, phi, psi, altitude, vx, vy))

    # Create full-color image from bytes
    image_cv = np.frombuffer(img_bytes, np.uint8)
    image_cv = np.ndarray.reshape(image_cv, (img_height, img_width, 3))
    image_ros = bridge.cv2_to_msgimg(image_cv)
    pub.publish(image_ros)
    

    #cv2.imshow('frame', image_cv)
    #cv2.waitKey(3)

    # Set up commands for a clockwise turn
    zap = 0
    phi = 0 
    theta = 0 
    gaz = 0 
    yaw = 1

    return (zap, phi, theta, gaz, yaw)

```
And got this error:

```
dave@dave:~/catkin_ws/ARDroneAutoPylot$ ./ardrone_autopylot
Setting locale to en_GB.UTF-8
===================+> 192.168.1.1
Input device Sony PLAYSTATION(R)3 Controller found
Input device js2 added
Starting thread video_stage
Set IP_TOS ok
Starting thread navdata_update
Starting thread ardrone_control
PA : MEMORY SPACE ALLOWED : 40 MB
Start thread thread_academy_upload
Start thread thread_academy
Start thread thread_academy_download 
Academy download stage resumed
Thread navdata_update in progress...

video stage thread initialisation

Video multisocket : init 2 sockets
Video multisocket : connecting socket 0 on port 5555 UDP
Video multisocket : connecting socket 1 on port 5555 TCP
Traceback (most recent call last):
  File "/home/dave/catkin_ws/ARDroneAutoPylot/autopylot_agent.py", line 24, in <module>
    import rospy
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/__init__.py", line 49, in <module>
    from .client import spin, myargv, init_node, \
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/client.py", line 54, in <module>
    import rospy.core
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/core.py", line 71, in <module>
    from rospy.names import *
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/names.py", line 86, in <module>
    _mappings = load_mappings(sys.argv)
AttributeError: 'module' object has no attribute 'argv'

```
I tried to fix it adding PySys_SetArgv(argc, argv); in autopylot_python_agent.c just before 	Py_Initialize(); also I have also added `int argc, char **argv` as arguements of the fuction agent init

```
void agent_init(int argc, char **argv)
{
		
	PySys_SetArgv(argc, argv);

	Py_Initialize();
	
	PyObject * pName = PyString_FromString(AGENT_MODULE_NAME);
	
	pModule = PyImport_Import(pName);
	
	Py_DECREF(pName);
```
	
but that did not solve the problem:
```

dave@dave:~/catkin_ws/ARDroneAutoPylot$ ./ardrone_autopylot
Setting locale to en_GB.UTF-8
===================+> 192.168.1.1
Input device Sony PLAYSTATION(R)3 Controller found
Input device js2 added
Starting thread video_stage
Set IP_TOS ok
Starting thread navdata_update
Starting thread ardrone_control
PA : MEMORY SPACE ALLOWED : 40 MB
Start thread thread_academy_upload
Start thread thread_academy
Start thread thread_academy_download 
Academy download stage resumed
Thread navdata_update in progress...

video stage thread initialisation

Video multisocket : init 2 sockets
Video multisocket : connecting socket 0 on port 5555 UDP
Video multisocket : connecting socket 1 on port 5555 TCP
Segmentation fault (core dumped)
```

Could you help me with that? Have you tried this before?  I do not know what that arguments (argc and argv) are. Any comment/idea is more than welcome.

Thanks in advance for your help, 

David

**Comment by simondlevy** [comment]
I'll look into this.  I don't use ROS, so it could take a while for me to get it set up and replicate the bug.

**Comment by simondlevy** [comment]
I found a three-lines-of-code solution [here](https://github.com/google/oauth2client/issues/642)  and tested it with the rospy import that was causing you problems.  I've put this additional code into the example [autopylot_agent.py](https://github.com/simondlevy/ARDroneAutoPylot/blob/master/autopylot_agent.py#L25-L30), but you can probably just copy-paste the three lines into your autopylot_agent.py, before the rospy import.

**Comment by davidsanchezf** [comment]
Dear Simon,

That solution compiled the executable file fine, but unfortunately, the message containing the frames do not get published. I do not find errors in my code, do you have any idea of what can be going on there? 

Thanks in advance for your help,

David

**Comment by simondlevy** [comment]
Sorry, I don't use ROS and so cannot help you.

**Comment by davidsanchezf** [comment]
Thanks so muh cfor your help anyhow, 

David

**Comment by alesolano** [comment]
Solved. The problem is that the ROS node needs to be created in the C file that calls the python agent. Don't really know why. To solve this, we import the `rospy` module from the `autopylot_python_agent.c` file and call the function `init_node` with the name of the node as an argument. Just as we had done in the python file, but in the C file using the functions from the [Python/C library](https://docs.python.org/2/c-api/index.html). And, of course, as Simon pointed in the last commits, before importing `rospy` we should tell the system that there will be no arguments, since it expects command-line argv. But _this will also be done in the C file_, before importing `rospy`.

### AUTOPYLOT_PYTHON_AGENT.C
```
(...)

void agent_init()
{
		
	Py_Initialize();

	int argc = 1;
        char * argv[1];
	PySys_SetArgv(argc, argv);

	PyObject *rospy = PyImport_ImportModule("rospy");
	if (!rospy)
	{
	    PyErr_Print();
	    printf("ERROR in ROSPY\n");
	    exit(1);
	}

	PyObject *init_node = PyObject_GetAttrString(rospy, "init_node");
	if (!init_node)
	{
	    PyErr_Print();
	    printf("ERROR in INIT_NODE\n");
	    exit(1);
	}

	PyObject *init_node_args = PyTuple_New(1);
	PyObject *node_name = PyString_FromString("dron_camera");	
	PyTuple_SetItem(init_node_args, 0, node_name);
	PyObject_CallObject(init_node, init_node_args);
	printf("Node created\n");

	
	PyObject * pName = PyString_FromString(AGENT_MODULE_NAME);
	
	pModule = PyImport_Import(pName);
	
	Py_DECREF(pName);
	
	if (pModule == NULL)
{
		PyErr_Print();
		error("Failed to load %s", AGENT_MODULE_NAME);
	}
	
	pFunc = PyObject_GetAttrString(pModule, AGENT_FUNCTION_NAME);
	
	if (!(pFunc && PyCallable_Check(pFunc)))
{
		if (PyErr_Occurred())
{
			PyErr_Print();
		}
		error("Cannot find function %s", AGENT_FUNCTION_NAME);
	}
	
	pArgs = PyTuple_New(12);
	
	pResult = PyTuple_New(5);
}

(...)
```

### AUTOPYLOT_AGENT.PY
```
(...)

import numpy as np
import cv2
import rospy
from sensor_msgs.msg import Image
import cv_bridge

pub = rospy.Publisher('frame', Image, queue_size=10)
bridge = cv_bridge.CvBridge()

def action(img_bytes, img_width, img_height, is_belly, \
    ctrl_state, vbat_flying_percentage, theta, phi, psi, altitude, vx, vy):

    # Report navigation data
    print('ctrl state=%6d battery=%2d%% theta=%+f phi=%+f psi=%+f altitude=%+3d vx=%f vy=%+f' % \
                          (ctrl_state, vbat_flying_percentage, theta, phi, psi, altitude, vx, vy))

    # Create full-color image from bytes
    image_cv = np.frombuffer(img_bytes, np.uint8)
    image_cv = np.ndarray.reshape(image_cv, (img_height, img_width, 3))
    image_ros = bridge.cv2_to_imgmsg(image_cv)
    pub.publish(image_ros)

    # Set up commands for a clockwise turn
    zap = 0
    phi = 0 
    theta = 0 
    gaz = 0 
    yaw = 1

    return (zap, phi, theta, gaz, yaw)
```

**Comment by davidsanchezf** [comment]
Thanks very much Ale, that works!!! Now I have the images packed on a message!! Really helpful!!!

David

**Comment by simondlevy** [comment]
Brilliant, thanks Ale!  I am about to add a link to your solution in the README for this project.

**Comment by alesolano** [comment]
Great! Thank YOU for this awesome project.
